### ISSUE TITLE
update Deck

### ISSUE THREAD

**Issue by jetjoshi** [atharvapatil22/PokerAI#17]
update Deck to allow input of an array of strings (deck sequence), and make that the deck.

**Comment by TiptonG** [comment]
Constructor now takes two additional optional arguments. If specified, the deckSequence will be parsed into the deck instead of the standard 52 cards, and no shuffling will be applied. The "deck.shuffle()" was removed from poker.py, as it is now redundant if shuffle=true, and unwanted if shuffle=false.

The constructor assumes that the deckSequence passed in will be an array of strings with the following format:
```"[<#|T|J|Q|K|A> <Sp|Cl|Di|He>]"```
- If this changes, PLEASE remember to update deck.py or it will not work.
- That being said, don't hesitate to change it, as it's probably easier to change the deck.py constructor than it is to change the entire testing structure format.

Fixed by #21
